### ISSUE TITLE
Erro at start

### ISSUE THREAD

**Issue by rodrigo-lm27** [gfaraj/super-bot#1]
When try start command "npm run start" get error 
>C:\super-bot-master\src\super-bot\SuperBot.js:47
    commands = {};
             ^

>SyntaxError: Unexpected token =
    at new Script (vm.js:83:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! super-bot@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the super-bot@1.0.0 start script.

**Comment by gfaraj** [comment]
Hi there! Did you execute "npm install" prior to running?

**Comment by rodrigo-lm27** [comment]
> 
> 
> Hi there! Did you execute "npm install" prior to running?

Hi, thanks for good work, yes i do npm install but continue this error, windows 10 64bits

**Comment by rodrigo-lm27** [comment]
>0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodejs\\node.exe',
1 verbose cli   'D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle super-bot@1.0.0~prestart: super-bot@1.0.0
6 info lifecycle super-bot@1.0.0~start: super-bot@1.0.0
7 verbose lifecycle super-bot@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle super-bot@1.0.0~start: CWD: D:\super-bot-master
10 silly lifecycle super-bot@1.0.0~start: Args: [ '/d /s /c', 'node .' ]
11 silly lifecycle super-bot@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle super-bot@1.0.0~start: Failed to exec start script
13 verbose stack Error: super-bot@1.0.0 start: `node .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid super-bot@1.0.0
15 verbose cwd D:\super-bot-master
16 verbose Windows_NT 10.0.17763
17 verbose argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error super-bot@1.0.0 start: `node .`
22 error Exit status 1
23 error Failed at the super-bot@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by gfaraj** [comment]
Ah, I think this may require you to upgrade Node to 12.X. I'm using version 12.9.
