### ISSUE TITLE
Error sending sticker.

### ISSUE THREAD

**Issue by edgaru** [gfaraj/super-bot#11]
**Describe the bug**
Error sending sticker (Store.CryptoLib.encryptE2EMedia is not a function)

**To Reproduce**
Sending a sticker.

**Comment by gfaraj** [comment]
It looks like Whatsapp have updated their website and removed (or moved) that function. I will look into it, thanks for reporting.

**Comment by gfaraj** [comment]
This is now fixed in the following commit:
53229cfb67f5f5bca71dca10cbf010014ae98ef0

Check it out!
