### ISSUE TITLE
Caption in attachment

### ISSUE THREAD

**Issue by KstmSoft** [gfaraj/super-bot#21]
Hello, i would like to set an caption in the attachment object for images.
Something like this:
```
    bot.respond({ attachment: {
        data: `data:image/jpeg;base64,${albumImage}`,
        mimetype: 'image/jpeg',
        //caption:`Album Image` <--------------
    }});
```

**Comment by gfaraj** [comment]
Hi there,

You can have the desired effect if you add a text property to the message:

`bot.respond({ text: 'Album Image', attachment: {
        data: ``data:image/jpeg;base64,${albumImage}``,
        mimetype: 'image/jpeg'
    }});`

Let me know if that works for you.

**Comment by KstmSoft** [comment]
Perfect, works like a charm!
Thanks so much.
