### ISSUE TITLE
Create Meme in Sticker

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [gfaraj/super-bot#25]
Examples :

https://meme-creator-live.netlify.com/

![image](https://user-images.githubusercontent.com/1152426/74593955-aa4b1400-500f-11ea-8c60-f76582522d40.png)

**Comment by gfaraj** [comment]
This is already possible using the meme and memed commands from this plugin:
https://github.com/gfaraj/super-bot/blob/master/plugins/imaging.js

Give it a try!
