### ISSUE TITLE
Problem in start

### ISSUE THREAD

**Issue by SubZer0GLX** [gfaraj/super-bot#9]
Hello i try to start but and dont know where i have to go to bot can read messages i run npm run start and it reply :

Starting SuperBot...
Loading plugins from path: C:\Users\subze\OneDrive\Área de Trabalho\super-bot-master\src\plugins
Loading plugin: admin.js...
Initializing plugin: admin.js...
Done plugin: admin.js...
Loading plugin: core.js...
Initializing plugin: core.js...
Done plugin: core.js...
Loading plugin: echo.js...
Initializing plugin: echo.js...
Done plugin: echo.js...
Loading plugin: evaluate.js...
Initializing plugin: evaluate.js...
Done plugin: evaluate.js...
Loading plugin: google.js...
Initializing plugin: google.js...
Done plugin: google.js...
Loading plugin: livescore.js...
Initializing plugin: livescore.js...
Done plugin: livescore.js...
Loading plugin: natural.js...
Initializing plugin: natural.js...
Done plugin: natural.js...
Loading plugin: poll.js...
Initializing plugin: poll.js...
Done plugin: poll.js...
Loading plugin: record.js...
Initializing plugin: record.js...
Done plugin: record.js...
Loading plugin: reminders.js...
Initializing plugin: reminders.js...
Done plugin: reminders.js...
Loading plugin: remove_bg.js...
Initializing plugin: remove_bg.js...
Done plugin: remove_bg.js...
Loading plugin: sticker.js...
Initializing plugin: sticker.js...
Done plugin: sticker.js...
Loading plugin: tell.js...
Initializing plugin: tell.js...
Done plugin: tell.js...
Loading plugin: translate.js...
Initializing plugin: translate.js...
Done plugin: translate.js...
Listening on port 3000

where i have to go to login with whatsapp?? thanks for help, and good project

**Comment by gfaraj** [comment]
Hi there, the root application is the bot service that listens for messages sent by the client interfaces. The client interfaces are applications of their own and are located in ./clients. You'll find the Whatsapp client there.

Just open a new terminal and go to the ./clients/whatsapp folder and install/run that app to open up the Whatsapp Web window.
